source  /opt/intel/dlstreamer/setupvars.sh
GST_DEBUG=h264parse:5,vaapi:5
/opt/intel/dlstreamer/gstreamer/bin/gst-launch-1.0 -vvvm udpsrc mtu=70000 timeout=40000000000 port=10023   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"22\\\"} ! fakesink async=false    \
udpsrc mtu=70000 timeout=40000000000 port=10024    !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"23\\\"} ! fakesink async=false    \
udpsrc mtu=70000 timeout=40000000000 port=10025   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"24\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10026   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"25\\\"} ! fakesink async=false    \
udpsrc mtu=70000 timeout=40000000000 port=10027   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"26\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10028   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"27\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10029   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"28\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10030   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"29\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10031   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"30\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10032   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"31\\\"} ! fakesink async=false      \
udpsrc mtu=70000 timeout=40000000000 port=10033   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"32\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10034   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"33\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10035   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"34\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10036   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"35\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10037   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"36\\\"} ! fakesink async=false   \
udpsrc mtu=70000 timeout=40000000000 port=10038   !   h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=5 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"37\\\"} ! fakesink async=false  

