source  /opt/intel/dlstreamer/setupvars.sh
# GST_DEBUG=h264parse:5,vaapi:5
# GST_DEBUG=7
/opt/intel/dlstreamer/gstreamer/bin/gst-launch-1.0 -m rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=1&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"1\\\"} ! fakesink     \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=2&subtype=0"    !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"2\\\"} ! fakesink     \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=3&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"3\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=4&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"4\\\"} ! fakesink     \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=5&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"5\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=6&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"6\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=7&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"7\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=8&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"8\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=9&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"9\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=10&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"10\\\"} ! fakesink       \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=11&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"11\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=12&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"12\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=13&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"13\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=14&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"14\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=15&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"15\\\"} ! fakesink    \
rtspsrc protocols=tcp location="rtsp://admin:admin#123@49.206.199.97:554/cam/realmonitor?channel=16&subtype=0"   !   queue  !   rtpjitterbuffer  !  rtph264depay   !  h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc    ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,width=312,height=312 ,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"16\\\"} ! fakesink   

