source  /opt/intel/dlstreamer/setupvars.sh
# GST_DEBUG=h264parse:5,vaapi:5
# GST_DEBUG=7
/opt/intel/dlstreamer/gstreamer/bin/gst-launch-1.0 -m udpsrc mtu=70000 timeout=40000000000 port=10000   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"1\\\"} ! fakesink     \
udpsrc mtu=70000 timeout=40000000000 port=10001    !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"2\\\"} ! fakesink     \
udpsrc mtu=70000 timeout=40000000000 port=10002   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"3\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10003   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"4\\\"} ! fakesink     \
udpsrc mtu=70000 timeout=40000000000 port=10004   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"5\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10005   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"6\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10006   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"7\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10007   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"8\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10008   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"9\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10009   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"10\\\"} ! fakesink       \
udpsrc mtu=70000 timeout=40000000000 port=10010   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"11\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10011   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"12\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10012   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"13\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10013   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"14\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10014   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"15\\\"} ! fakesink    \
udpsrc mtu=70000 timeout=40000000000 port=10015   !   queue  !    h264parse update-timecode=true ! vaapih264dec   !   vaapipostproc deinterlace-method=0  deinterlace-mode=2   ! videoconvert ! capsfilter  caps="video/x-raw,format=BGR"  ! videorate drop-only=true  max-rate=1 silent=false  ! video/x-raw,framerate=1/1 !  queue  ! gvapython module=xeon_gva_python_3.py class=custom_accumulator function=process_frame arg={\\\"cam_no\\\":\\\"16\\\"} ! fakesink   

